name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Groundfloor
      run: mkdir build ** cd build && cmake .. && make Groundfloor
    - name: Jumpropes
      run: mkdir build ** cd build && cmake .. && make Jumpropes
    - name: Jumpknots
      run: mkdir build ** cd build && cmake .. && make Jumpknots
    - name: MySQL
      run: mkdir build ** cd build && cmake .. && make MySQLBooks
