name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Groundfloor
      run: mkdir -p build && cd build && cmake .. && make Groundfloor
    - name: Jumpropes
      run: mkdir -p build && cd build && cmake .. && make Jumpropes
    - name: Jumpknots
      run: mkdir -p build && cd build && cmake .. && make Jumpknots
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        path: "*.a"
