name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Groundfloor
      run: mkdir -p build && cd build && cmake .. && make Groundfloor
    - name: Jumpropes
      run: mkdir -p build && cd build && cmake .. && make Jumpropes
    - name: Artifact Groundfloor
      uses: actions/upload-artifact@v4
      with:
        name: Groundfloor
        path: "build/libGroundfloor/*.a"
    - name: Artifact Jumpropes
      uses: actions/upload-artifact@v4
      with:
        name: Jumpropes
        path: "build/libJumpropes/*.a"
